### ISSUE TITLE
"\C-k" and "\C-a" are not binded on some Linux distro

### ISSUE THREAD

**Issue by ghost** [Sbozzolo/vterm-extra#1]
When calling vterm-extra-edit-command-in-new-buffer, \C-a\C-k will be send to the terminal in order
to move the cursor to the begining of the line then kill the line, this is not the default behavious in some
Linux distro like ArchLinux. 
In  order to make vterm-extra-edit-command-in-new-buffer wont work as expected, user should put

```bash
bind "\C-k":kill-line
bind "\C-a":beginning-of-line
```

in .bashrc.
Maybe mention this in the Readme?

**Comment by Sbozzolo** [comment]
Thanks, we don't really `C-a` (we can use `vterm-beginning-of-line`), but we need `C-k`. I added some additional explanation in readme and docstrings.
